### PR TITLE
i had a child

### PR DESCRIPTION
**Pull request by the-spui-ninja**

### CODE REVIEW

**Comment by michihdeu** [comment]
@jteresco Be aware that there is a new (but empty) list file? Does a empty list file work, @yakra ?

**Comment by yakra** [comment]
Interesting. I *believe* an empty .list file should work, but that's just the kind of place an unexpected bug could be lurking. I'll test it out.

**Comment by yakra** [comment]
C++ is fine, but siteupdate.py crashes on 0-byte list files.
I don't know if this file is 0 bytes, or a single line feed or what, but that's something to watch out for. A workaround should be easy enough to add to siteupdate.py.

**Comment by jteresco** [comment]
I'd also want to think about things like divide-by-zero errors on the web front end.

**Comment by yakra** [comment]
Wait, I believe there are some existing .list files with no valid lines. Those should let us test the same things. I'll look up which ones they are.

**Comment by yakra** [comment]
benjamingrove47
capecodder
Qiviuq

**Comment by jteresco** [comment]
Given that we already had 0-mile users and I haven't heard of any serious problems, I think we can go for it.

**Comment by yakra** [comment]
Anyway -- congrats on the Mini Spui Ninja!

**Comment by the-spui-ninja** [comment]
Thanks! I would have waited to put in her file if I had known it would cause chaos… my brains not working well this week!

**Pull request merged**
