### PR TITLE
michih list file

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by michihdeu** [comment]
Hell....

**Comment by jteresco** [comment]
Leaving this out for now because of the conflicts.

**Comment by michihdeu** [comment]
I've deleted my offline data and downloaded again. Can't sync because no permission (like for Web repository). Opened GitShell:

 ```
C:\Users\michael\Documents\GitHub\UserData [master ↑]> git rebase
Current branch master is up to date.
C:\Users\michael\Documents\GitHub\UserData [master ↑]> git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
C:\Users\michael\Documents\GitHub\UserData [master ↑]> git push
remote: Permission to TravelMapping/UserData.git denied to michihdeu.
fatal: unable to access 'https://github.com/TravelMapping/UserData.git/': The re
quested URL returned error: 403
C:\Users\michael\Documents\GitHub\UserData [master ↑]> git remote -v
origin  https://github.com/TravelMapping/UserData.git (fetch)
origin  https://github.com/TravelMapping/UserData.git (push)
```
GitHub helps has an issue with "403": https://help.github.com/articles/https-cloning-errors/

GitHub Desktop version is up to date. Remote is correct (see above). I have only one user account...

Any idea?

**Comment by jteresco** [comment]
Have you been able to resolve this?  Since I assume you only care about tracking changes in your own file, I think there's no harm in deleting your fork and recreating it in the web interface, and then cloning a brand new copy of it to your local machine.

**Comment by michihdeu** [comment]
I've no idea what I've done but it temporarily worked. However, I was confused and managed that it didn't work again. I often got a message "You have no permission to TravelMapping" but for any reason it seems that it works again. Dunno why the first attempts after deleting the fork are put to the old pull request but there's a new pull request now... However, it always the same file. I'll close this one but if the new pull doesn't work, please try with this one...

**Pull request closed without merging**
