### PR TITLE
Update jayhawkco.list

### PR DESCRIPTION
**Pull request by chrislwillers**
Redoing the Flaming Gorge road trip as it looks like it was closed.  I had done one edit, realized I missed something, so I closed that pull request and opened another.  This set of edits should be correct.

### CODE REVIEW

**Comment by yakra** [comment]
The DIFFs look the same...
https://github.com/TravelMapping/UserData/pull/4058/commits/05481c9419f0fa79ed8a43a54e8efc5d6bf6e26a#diff-bc92668e64bcb675cd980099989de32c
https://github.com/TravelMapping/UserData/pull/4056/commits/7b3e54bc98f1d04df81dbc7f7f8a770a326ec1be#diff-bc92668e64bcb675cd980099989de32c
Is everything as intended?

**Comment by chrislwillers** [comment]
Looks to be.

**Comment by yakra** [comment]
OK. Maybe you didn't actually miss anything then; if you're OK with how everything looks now I can go ahead & merge it in.

**Comment by chrislwillers** [comment]
sounds great.  Thanks

**Pull request merged**
