### PR TITLE
Update 25or6to4.list

### PR DESCRIPTION
**Pull request by TXStormchaser**

### CODE REVIEW

**Comment by jteresco** [comment]
@TXStormchaser Looks like there are some merge conflicts here.

**Comment by TXStormchaser** [comment]
I saw that, but it won't tell me what the actual conflict is, and it won't give me any options to resolve the conflict.

**Comment by jteresco** [comment]
Looks like it's good now.  It will be merged in for tomorrow's update.

**Comment by TXStormchaser** [comment]
I just pulled the rail edit I made. That looks like it did the trick. Thanks!

**Pull request merged**
