### PR TITLE
Update Buckeye.list

### PR DESCRIPTION
**Pull request by buckeye111**

### CODE REVIEW

**Comment by jteresco** [comment]
Looks like we have some merge conflicts, @buckeye111

**Comment by buckeye111** [comment]
Oops!

What would you like me to do? I apologize for any inconvenience - I thought
I followed the directions but it seems I haven't.

**Comment by buckeye111** [comment]
Alright, @jteresco - I believe I've got it sorted!
I understand if I'll have to wait for the next update to see my stats - again, I apologize for the hassle!

**Comment by jteresco** [comment]
Yes, it looks like the merge conflicts are resolved.  It will go in tonight.  Thanks.

**Pull request merged**
