### PR TITLE
Create pnrrth.list

### PR DESCRIPTION
**Pull request by pnrrth**
Add my list file from CHM

### CODE REVIEW

**Comment by jteresco** [comment]
I'll run an update shortly so you can see your maps and log files.

**Comment by pnrrth** [comment]
Thanks Jim.  Glad to see you all are working on a replacement for the
seemingly defunct CHM.  I am a programmer by trade (ASP.NET/Microsoft
products mostly), but might be able to help out in some areas.

I also had tried to contact CHM several times offering to help build out
the SC highways.  I would love to be able to get those into the system at
some point in time so if there is a way I can help do that, let me know!

Tim

On Fri, Aug 28, 2015 at 1:05 PM, Jim Teresco <notifications@github.com>
wrote:

> I'll run an update shortly so you can see your maps and log files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TravelMapping/UserData/pull/27#issuecomment-135833622>
> .
>



-- 
Tim Huemmer
Webmaster & Owner
RRPictureArchives.NET

**Comment by jteresco** [comment]
I'm sure there are plenty of ways you'll be able to help out.  If you aren't there already, please join us on the AARoads forum "Clinched Highway Mapping" board, where we're collaborating until the new system gets onto its own site.

**Comment by pnrrth** [comment]
Thanks, I applied for an account on the forum!

On Fri, Aug 28, 2015 at 2:07 PM, Jim Teresco <notifications@github.com>
wrote:

> I'm sure there are plenty of ways you'll be able to help out. If you
> aren't there already, please join us on the AARoads forum "Clinched Highway
> Mapping" board, where we're collaborating until the new system gets onto
> its own site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TravelMapping/UserData/pull/27#issuecomment-135849496>
> .
>



-- 
Tim Huemmer
Webmaster & Owner
RRPictureArchives.NET

**Comment by pnrrth** [comment]
Jim,

I applied on the forum and asked if I could help with the SC Highways, but
it doesn't look like my request for help was too well received at the
moment.  One of the reasons given was lack of tooling.  I did download the
code for the wpteditor and figured out how to use it to create a few SC
Highway waypoint files.  I think I got them right, but don't have a good
way to test them at the moment.

In looking at the code, I wondered if there were any outstanding/known
issues with it?  Here are a few things I noticed:

Does it work in all browsers, or just certain ones?
A follow on to this is that I noticed that a lot of the code could be
optimized using a library such as JQuery and this could potentially solve
some cross browser issues if they happen to exist

I noticed that re-arranging the sortable doesn't always seem to reconfigure
the route (i.e. I tried to insert a +X___ waypoint in in the middle to make
the route better follow the course of the road, but I couldn't get it to
place the point in the right place)

A nice new feature to add would be a way to clear all the waypoints for an
existing list.  This would allow you to create one file for a highway,
clear the list with one click, then start on the next one.


Sorry to bombard you with a lot of information.  I am looking for some
historical reference to these tools before attempting to mess with the code
for the wpteditor.

Thanks and have a great Sunday!

Tim


On Fri, Aug 28, 2015 at 2:07 PM, Jim Teresco <notifications@github.com>
wrote:

> I'm sure there are plenty of ways you'll be able to help out. If you
> aren't there already, please join us on the AARoads forum "Clinched Highway
> Mapping" board, where we're collaborating until the new system gets onto
> its own site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TravelMapping/UserData/pull/27#issuecomment-135849496>
> .
>



-- 
Tim Huemmer
Webmaster & Owner
RRPictureArchives.NET

**Pull request merged**
