### PR TITLE
KC and RMNP trips

### PR DESCRIPTION
**Pull request by sipes23**
New mileage and a few fixes.

### CODE REVIEW

**Comment by jteresco** [comment]
Please resolve conflicts so I can merge this in cleanly.

**Comment by sipes23** [comment]
I'll take care of it. Probably tomorrow. I don't know what happened.

Pete

**Comment by Markkos1992** [comment]
Try taking the file you submitted and putting it directly in the TravelMapping:master version of your list file.  That should create a patch in your repository, and then from there you should pull request that patch either directly into TravelMapping:master or into your own master first then TravelMapping:master.

Hope this helps.

**Comment by jteresco** [comment]
@sipes23 ok to close this one?

**Comment by sipes23** [comment]
Yes.

**Pull request closed without merging**
