### PR TITLE
michih update swe

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by jteresco** [comment]
This is showing conflicts for some reason.

**Comment by michihdeu** [comment]
I've check it manually and don't see anything. What kind of conflict does occur?

**Comment by jteresco** [comment]
Not sure, but github is giving me "This branch has conflicts that must be resolved".  I'm guessing it will be resolved easily enough, but it didn't get in in time for this afternoon's site update.  Let me try the command line to resolve it.

**Comment by jteresco** [comment]
Very strange - I never had to fix anything to resolve the conflict.

**Comment by michihdeu** [comment]
Ah, got it. I had a similar conflict (same message) with hwy data when I tried to make my 3rd or 4th pull request. I've deleted all local repository files on my PC et cetera. I don't know why but it worked after many attempts........

If I got it right, you could finally merge the file and it will be online with the next site update?

**Comment by jteresco** [comment]
Yes, it's merged and will be in the next site update tonight or tomorrow.

**Pull request merged**
