### PR TITLE
CA business trip

### PR DESCRIPTION
**Pull request by ntallyn**
Not sure why the AUS-SA changes are showing. They already are merged...

### CODE REVIEW

**Comment by Markkos1992** [comment]
It looks like you may be updating a March 2020 version of your list file from looking at the commit before your last one.

**Comment by jteresco** [comment]
Waiting to see what to do about the conflicts before I do anything with this.  @ntallyn

**Comment by ntallyn** [comment]
I'm not sure where the old file came from. I just got a new laptop, and copied the file over. But it should have already been on the branch when I created the local repo, anyway. I'll have to look into this a little more to figure out what's up.

**Comment by jteresco** [comment]
I'm going to close this one, @ntallyn please reopen this or create a new PR when you're ready to try this again.

**Pull request closed without merging**
