### PR TITLE
Added business loops and usava mileage

### PR DESCRIPTION
**Pull request by Thing342**

### CODE REVIEW

**Comment by jteresco** [comment]
It looks like this has a lot of extra stuff, not just your file.

**Comment by ssoworld** [comment]
Did you do a remote merge of your fork before your push?  I remember because I had this problem myself in the past. (I ended up nuking my fork to fix)

**Comment by Thing342** [comment]
Nuke my fork and tried again with a new pull request. (Git is hard)

**Comment by ssoworld** [comment]
I found that when I want to do test of my data or program runs I just have a single computer (a Windows box with the Github app) handle the synchronizations and I use a synch program (Beyond Compare 4) to distribute - both fork and main.  Don't fork/remote merge unless you want to do work within a day of that action.  Then check in your changes right away to avoid additional pains.

**Comment by jteresco** [comment]
The new one looks good, thanks.

**Pull request closed without merging**
