### PR TITLE
michih + bubaclex

### PR DESCRIPTION
**Pull request by michihdeu**
@jteresco I got a list file for railways from bubaclex via mail. I hope to get more user feedback this way. bubaclex already sent you a file via email but it is not online. Not on the site nor on Github. I guess it's because you don't accept email submission yet? Nonetheless, the file in my pull is the right one. There are still some data errors, I will get - and submit via Github - an updated file in the next days.

### CODE REVIEW

**Comment by jteresco** [comment]
Thanks.  The system I use to handle email submissions doesn't know anything about the railways, so the list ended up in the highway data list file.  Looks like I should remove bubaclex_train.list from there.

**Comment by jteresco** [comment]
It looks like I didn't catch it as a new file, so it never made it past by own staging area, not into GitHub.  Anyway, once we switch to .rlist extensions I can automate email submissions.

**Comment by michihdeu** [comment]
Do you need to do anything manually to add new users? I thought there was something, but when I simply run data check, the new file is automatically loaded.

**Comment by jteresco** [comment]
Since they're not coming in through GitHub, I have to remember to do a "git add" for new files.  My script generates a warning, but when I see names that are familiar, I admit I don't always pay attention to the warnings.

**Comment by michihdeu** [comment]
> Looks like I should remove bubaclex_train.list from there.

Yes. Thanks!

**Pull request merged**
