### PR TITLE
Create 420Traveler  #2

### PR DESCRIPTION
**Pull request by 420Traveler**

### CODE REVIEW

**Comment by michihdeu** [comment]
@420Traveler your file is missing the .list file extension, see https://github.com/TravelMapping/UserData/pull/2915

**Comment by 420Traveler** [comment]
Can someone help me fix this, thanks

**Comment by jteresco** [comment]
You want to merge in the filename change I made in #2915 and start editing that file instead.

Of course you're also welcome to email files to me (use travmap@teresco.org) and avoid GitHub altogether, in which case it doesn't really matter if it has the wrong extension, since I can easily fix it when I move it into place.

**Comment by 420Traveler** [comment]
@jteresco will the ones i added today be added into the one i crrated yesterday? Thanks

**Comment by jteresco** [comment]
I've pasted these into your file, soon to be here on GitHub and in place for tonight's update.  You'll want to make sure you use the version in GitHub as your starting point for any further updates.

**Pull request closed without merging**
