### PR TITLE
cinx / michih

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by michihdeu** [comment]
@jteresco please update the test DB (**w/o** hwy_data from my last pull request)

**Comment by jteresco** [comment]
I haven't pulled in the DEU split changes, so the test DB update will run with the same data as the regular update.

**Comment by michihdeu** [comment]
@jteresco Thanks. My data is updated but cinx is still missing: http://tmtest.teresco.org/stat.php?u=michih&units=km&dbname=TravelMappingTest (do you have to add him anywhere as a new traveler on the test DB too?)

**Comment by jteresco** [comment]
I didn't realize I was only bringing in specific user lists.  I added cinx and ran again.

**Pull request merged**
